#!/usr/bin/env bash

SECONDS=0
out=$( { time ucvm_query -m muscal -f $UCVM_INSTALL_PATH/conf/ucvm.conf < MSCAL_test_points_deep.txt > MSCAL_test_points_deep.final ; } 2>&1 )
echo "$out" >> MSCAL_test_points_deep.final
echo "Elapsed: ${SECONDS}s" >> MSCAL_test_points_deep.final


SECONDS=0
out=$( { time ucvm_query -m muscal -f $UCVM_INSTALL_PATH/conf/ucvm.conf < MSCAL_test_points_shallow.txt > MSCAL_test_points_shallow.final ; } 2>&1 )
echo "$out" >> MSCAL_test_points_shallow.final
echo "Elapsed: ${SECONDS}s" >> MSCAL_test_points_shallow.final

